add package manager logs path

diff --git a/.github/workflows/unity-build.yml b/.github/workflows/unity-build.yml
--- a/.github/workflows/unity-build.yml
+++ b/.github/workflows/unity-build.yml
@@ -61,12 +61,12 @@ jobs:
           echo "UNITY_PROJECT_PATH: ${UNITY_PROJECT_PATH}" # Expected to be empty at this point
 
           if [ -z "${UNITY_HUB_PATH}" ]; then
-            echo "Error: UNITY_HUB_PATH is not set"
+            echo "::error::UNITY_HUB_PATH is not set"
             exit 1
           fi
 
           if [ "${{ matrix.unity-version }}" != "none" ] && [ -z "${UNITY_EDITOR_PATH}" ]; then
-            echo "Error: UNITY_EDITOR_PATH is not set"
+            echo "::error::UNITY_EDITOR_PATH is not set"
             exit 1
           fi
       - name: Activate License
@@ -80,28 +80,35 @@ jobs:
         shell: bash
         run: |
           HUB_LOG_PATH=$(unity-cli hub-logs)
+          PACKAGE_MANAGER_LOG_PATH=$(unity-cli package-manager-logs)
           LICENSING_CLIENT_LOG_PATH=$(unity-cli licensing-client-logs)
           LICENSING_AUDIT_LOG_PATH=$(unity-cli licensing-audit-logs)
           
           echo "Hub Log Path: ${HUB_LOG_PATH}"
+          echo "Package Manager Log Path: ${PACKAGE_MANAGER_LOG_PATH}"
           echo "Licensing Client Log Path: ${LICENSING_CLIENT_LOG_PATH}"
           echo "Licensing Audit Log Path: ${LICENSING_AUDIT_LOG_PATH}"
           
           # verify that the log files exist
           if [ ! -f "${LICENSING_CLIENT_LOG_PATH}" ]; then
-            echo "Error: Licensing Client log file does not exist at ${LICENSING_CLIENT_LOG_PATH}"
+            echo "::error::Licensing Client log file does not exist at ${LICENSING_CLIENT_LOG_PATH}"
+            exit 1
+          fi
+          
+          if [ ! -f "${PACKAGE_MANAGER_LOG_PATH}" ]; then
+            echo "::error::Package Manager log file does not exist at ${PACKAGE_MANAGER_LOG_PATH}"
             exit 1
           fi
           
           if [ ! -f "${LICENSING_AUDIT_LOG_PATH}" ]; then
-            echo "Error: Licensing Audit log file does not exist at ${LICENSING_AUDIT_LOG_PATH}"
+            echo "::error::Licensing Audit log file does not exist at ${LICENSING_AUDIT_LOG_PATH}"
             exit 1
           fi
           
           if [ ! -f "${HUB_LOG_PATH}" ]; then
             echo "::warning:: Hub log file does not exist at ${HUB_LOG_PATH}"
             
-            ALT_HUB_LOG_PATH="${UNITY_HUB_PATH}/Logs/UnityHub.log"
+            ALT_HUB_LOG_PATH="${UNITY_HUB_PATH}/logs/info-log.json"
             echo "Checking alternative Hub log path: ${ALT_HUB_LOG_PATH}"
             
             if [ -f "${ALT_HUB_LOG_PATH}" ]; then
@@ -109,7 +116,7 @@ jobs:
               exit 0
             else
               # try ~/.config/UnityHub/logs/UnityHub.log
-              ALT_HUB_LOG_PATH="~/.config/UnityHub/logs/UnityHub.log"
+              ALT_HUB_LOG_PATH="~/.config/UnityHub/logs/info-log.json"
               echo "Checking alternative Hub log path: ${ALT_HUB_LOG_PATH}"
               
               if [ -f "${ALT_HUB_LOG_PATH}" ]; then
@@ -118,19 +125,11 @@ jobs:
               fi
             fi
             
-            echo "::error:: Hub log file does not exist at any known location"
+            # list all .log and .json files in ~/.config/UnityHub/ directory
+            echo "Listing all .log and .json files in ~/.config/UnityHub/ directory:"
+            ls -l ~/.config/UnityHub/*.log ~/.config/UnityHub/*.json || true
             
-            # search the whole disk for *.UnityHub.log files and print their paths
-            echo "Searching for UnityHub.log files on the system:"
-            paths=$(find / -type f -name "*.UnityHub.log" 2>/dev/null)
-            if [ -z "$paths" ]; then
-              echo "No UnityHub.log files found on the system."
-            else
-              echo "Found UnityHub.log files at the following locations:"
-              for path in $paths; do
-                echo "$path"
-              done
-            fi
+            echo "::error:: Hub log file does not exist at any known location"
             exit 1
           fi
       - name: Create Unity Project
@@ -144,7 +143,7 @@ jobs:
         shell: bash
         run: |
           if [ -z "${UNITY_PROJECT_PATH}" ]; then
-            echo "Error: UNITY_PROJECT_PATH is not set"
+            echo "::error::UNITY_PROJECT_PATH is not set"
             exit 1
           fi
           # check if the project can be built. Only Unity 2019.4+ and newer majors support the build pipeline package
